---
driver:
  name: vagrant
  vm_hostname: ldm.local
 
provisioner:
  name: chef_zero
  product_name: cinc
  download_url: https://omnitruck.cinc.sh/install.sh

  #verifier:
  #name: inspec

platforms:
  - name: bento/rockylinux-9
    config:
    disksize:
      size='100GB'
    attributes:
      firewall:
        allow_ssh: true
        #    driver_config:
        #password: vagrant
        #transport:
        #username: vagrant
        #password: vagrant

suites:
  - name: default
    run_list:
      - recipe[ldm::default]
    attributes:
    verifier:
      inspec_tests:
        - test/smoke/default
