---
driver:
  name: vagrant
  vm_hostname: ldm.local

provisioner:
  name: chef_solo
  
verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[ldm::default]
    attributes:
    verifier:
      inspec_tests:
        - test/smoke/default
